const POST_UPLOAD_START = "POST_UPLOAD_START";
const POST_UPLOAD_END = "POST_UPLOAD_END";
const FETCH_POST_LIST = "FETCH_POST_LIST";

const INSERT_POST_OBJECT = "INSERT_POST_OBJECT";
const DELETE_POST_OBJECT = "DELETE_POST_OBJECT";

export {
  POST_UPLOAD_START,
  POST_UPLOAD_END,
  
  FETCH_POST_LIST,
  INSERT_POST_OBJECT,
  DELETE_POST_OBJECT,
}